title: DROID Docs
description: Developer documentation for recreating the DROID platform setup.
theme: just-the-docs

url: https://peterdavidfagan.github.io/DROID # this url not being used right now
color_scheme: r2d2 # TODO: update name to DROID

aux_links:
  Official GitHub Repository: https://github.com/AlexanderKhazatsky/R2D2
