name: build nuc fr3 container and host on ghcr.io

on:
  push:
    branches: ['main']
    paths:
      - .gitmodules
      - r2d2/**
      - .docker/nuc/*
      - .github/workflows/build_container_nuc_fr3
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  ORG_NAME: peterdavidfagan
  IMAGE_NAME: droid_nuc

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: .docker/nuc/Dockerfile.nuc_fr3
          push: true
          no-cache: true
          tags: ${{ env.REGISTRY }}/${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}:fr3
